name: Gitleaks Scan
on:
  pull_request:
  
permissions:
  contents: read
  pull-requests: read
  security-events: write
  
jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Run Gitleaks Scan
        uses: mr-r0w07/test-workflows/.github/composite-actions/gitleaks@main
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
